#!/usr/bin/env node

import fs from 'node:fs';
import path from 'node:path';
import matter from 'gray-matter';

const appDir = path.resolve(import.meta.dirname, '..');
const sourceDir = path.resolve(appDir, 'src/content/docs');
const outputDir = path.resolve(sourceDir, 'generated');

fs.mkdirSync(outputDir, { recursive: true });

const sourceFiles = fs.readdirSync(sourceDir).filter((f) => f.endsWith('.md'));

for (const file of sourceFiles) {
  const filePath = path.join(sourceDir, file);
  const raw = fs.readFileSync(filePath, 'utf-8');
  const { data, content } = matter(raw);

  const slug = path.basename(file, '.md');
  const title = String(data.title ?? slug);
  const description = String(data.description ?? '');
  const body = content.trim();

  const output = `// Auto-generated by scripts/compile-docs.mts from content/docs/${file}.
// Do not edit manually — edit the source .md file instead.

export const title = ${JSON.stringify(title)};
export const description = ${JSON.stringify(description)};
export const body = ${JSON.stringify(body)};
`;

  fs.writeFileSync(path.join(outputDir, `${slug}.ts`), output);
}

console.log(
  `Compiled ${sourceFiles.length} doc${sourceFiles.length === 1 ? '' : 's'} to ${path.relative(appDir, outputDir)}`,
);
