#!/usr/bin/env node

import fs from 'node:fs';
import path from 'node:path';
import { iconFamilies } from '../src/data/icon-families.ts';

const appDir = path.resolve(import.meta.dirname, '..');
const packagesDir = path.resolve(appDir, '../../packages');
const outputDir = path.resolve(appDir, 'src/data/generated');

const entries: string[] = [];

for (const family of Object.values(iconFamilies)) {
  if (family.licence !== 'pro') continue;

  const configPath = path.join(packagesDir, family.packageDir, '.yo-rc.json');
  if (!fs.existsSync(configPath)) continue;

  const config = JSON.parse(fs.readFileSync(configPath, 'utf-8'));
  const meta = config['generator-react-native-vector-icons'];
  if (!meta?.postScriptName || !meta?.fontFileName) continue;
  const { postScriptName, fontFileName } = meta;

  const ttfPath = path.join(appDir, 'rnvi-fonts', family.packageDir, `${fontFileName}.ttf`);
  if (!fs.existsSync(ttfPath)) continue;

  const relativePath = path.relative(outputDir, ttfPath);
  entries.push(`  ${JSON.stringify(postScriptName)}: require('${relativePath}'),`);
}

const output = `// Auto-generated by scripts/generate-pro-fonts.mts
// Do not edit manually.

export const proFonts: Record<string, number> = {
${entries.join('\n')}
};
`;

fs.mkdirSync(outputDir, { recursive: true });
fs.writeFileSync(path.join(outputDir, 'pro-fonts.generated.ts'), output);

console.log(`Generated pro-fonts.generated.ts: ${entries.length} pro fonts found`);
