#!/usr/bin/env node

import fs from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';
import { iconFamilies } from '../src/data/icon-families.ts';

const require = createRequire(import.meta.url);
const outputDir = path.resolve(import.meta.dirname, '../src/data/generated');

const imports: string[] = [];
const registryEntries: string[] = [];
const availableFamilies: string[] = [];
const stubFamilies: string[] = [];

for (const [key, family] of Object.entries(iconFamilies)) {
  const packageName = family.packageName;

  let available = false;
  try {
    require.resolve(packageName);
    available = true;
  } catch {
    // Package not installed or not resolvable
  }

  if (available) {
    imports.push(`import { ${family.componentName} } from '${packageName}';`);
    registryEntries.push(`  ${key}: ${family.componentName},`);
    availableFamilies.push(key);
  } else {
    stubFamilies.push(key);
    registryEntries.push(`  ${key}: createStubIcon('${key}'),`);
  }
}

const output = `// Auto-generated by scripts/generate-icon-registry.mts
// Do not edit manually.

import type { ComponentType } from 'react';
import { Text, View } from 'react-native';

${imports.join('\n')}

export type IconComponentProps = {
  name: string;
  size?: number;
  color?: string;
};

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type IconComponent = ComponentType<any>;

function createStubIcon(familyName: string): IconComponent {
  return function StubIcon({ size = 24, color = '#666' }: IconComponentProps) {
    return (
      <View style={{ width: size, height: size, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(139, 92, 246, 0.1)', borderRadius: 4 }}>
        <Text style={{ fontSize: size * 0.25, color, fontWeight: '600' }}>PRO</Text>
      </View>
    );
  };
}

export const iconRegistry: Record<string, IconComponent> = {
${registryEntries.join('\n')}
};
`;

fs.mkdirSync(outputDir, { recursive: true });
fs.writeFileSync(path.join(outputDir, 'icon-registry.generated.tsx'), output);

console.log(`Generated icon-registry.generated.tsx:`);
console.log(`  Available: ${availableFamilies.length} families`);
if (stubFamilies.length > 0) {
  console.log(`  Stubbed (Pro): ${stubFamilies.length} families (${stubFamilies.join(', ')})`);
}
