#!/usr/bin/env node

import fs from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';
import { type IconFamily, iconFamilies } from '../src/data/icon-families.ts';

const require = createRequire(import.meta.url);
const appDir = path.resolve(import.meta.dirname, '..');
const packagesDir = path.resolve(appDir, '../../packages');
const outputDir = path.resolve(appDir, 'src/data/generated');

const isPackageAvailable = (packageName: string): boolean => {
  try {
    require.resolve(packageName);
    return true;
  } catch {
    return false;
  }
};

const buildProFontEntry = (family: IconFamily): string | null => {
  if (family.licence !== 'pro') return null;

  const configPath = path.join(packagesDir, family.packageDir, '.yo-rc.json');
  if (!fs.existsSync(configPath)) return null;

  const config = JSON.parse(fs.readFileSync(configPath, 'utf-8'));
  const meta = config['generator-react-native-vector-icons'];
  if (!meta?.postScriptName || !meta?.fontFileName) return null;

  const ttfPath = path.join(appDir, 'rnvi-fonts', family.packageDir, `${meta.fontFileName}.ttf`);
  if (!fs.existsSync(ttfPath)) return null;

  const relativePath = path.relative(outputDir, ttfPath);
  return `  ${JSON.stringify(meta.postScriptName)}: require('${relativePath}'),`;
};

const registryImports: string[] = [];
const registryEntries: string[] = [];
const glyphmapIndex: Record<string, Record<string, number>> = {};
const proFontEntries: string[] = [];
const stubFamilies: string[] = [];

for (const [key, family] of Object.entries(iconFamilies)) {
  if (isPackageAvailable(family.packageName)) {
    registryImports.push(`import { ${family.componentName} } from '${family.packageName}';`);
    registryEntries.push(`  ${key}: ${family.componentName},`);
  } else {
    registryEntries.push(`  ${key}: PreviewStubIcon,`);
    stubFamilies.push(key);
  }

  const glyphPath = path.join(packagesDir, family.packageDir, 'glyphmaps', `${family.componentName}.json`);
  if (fs.existsSync(glyphPath)) {
    glyphmapIndex[family.componentName] = JSON.parse(fs.readFileSync(glyphPath, 'utf-8'));
  }

  const proFontEntry = buildProFontEntry(family);
  if (proFontEntry) proFontEntries.push(proFontEntry);
}

const registryOutput = `// Auto-generated by scripts/generate-app-data.mts
// Do not edit manually.

import type { ComponentType } from 'react';
import { PreviewStubIcon } from '@/components/PreviewStubIcon';

${registryImports.join('\n')}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type IconComponent = ComponentType<any>;

export const iconRegistry: Record<string, IconComponent> = {
${registryEntries.join('\n')}
};
`;

const proFontsOutput = `// Auto-generated by scripts/generate-app-data.mts
// Do not edit manually.

export const proFonts: Record<string, number> = {
${proFontEntries.join('\n')}
};
`;

fs.mkdirSync(outputDir, { recursive: true });
fs.writeFileSync(path.join(outputDir, 'icon-registry.generated.tsx'), registryOutput);
fs.writeFileSync(path.join(outputDir, 'glyphmapIndex.json'), JSON.stringify(glyphmapIndex, null, 2));
fs.writeFileSync(path.join(outputDir, 'pro-fonts.generated.ts'), proFontsOutput);

const totalIcons = Object.values(glyphmapIndex).reduce((sum, family) => sum + Object.keys(family).length, 0);
console.log('Generated app data:');
console.log(`  glyphmapIndex.json: ${Object.keys(glyphmapIndex).length} families, ${totalIcons} icons`);
console.log(
  `  icon-registry.generated.tsx: ${registryImports.length} available, ${stubFamilies.length} stubbed${stubFamilies.length > 0 ? ` (${stubFamilies.join(', ')})` : ''}`,
);
console.log(`  pro-fonts.generated.ts: ${proFontEntries.length} fonts`);
