---
name: "\U0001F41B Bug report"
description: Report a bug
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Before filing a bug report:
        - Review the documentation: https://github.com/react-native-vector-icons/react-native-vector-icons
        - Search for existing issues (including closed issues): https://github.com/oblador/react-native-vector-icons/issues?q=is%3Aissue+

  - type: dropdown
    id: generation
    attributes:
      label: Which package are you using?
      options:
        - "@react-native-vector-icons/*"
        - react-native-vector-icons
    validations:
      required: true

  - type: dropdown
    attributes:
      label: What platform(s) does this occur on?
      multiple: true
      options:
        - Android
        - iOS
        - web
    validations:
      required: true

  - type: input
    attributes:
      label: Minimal reproducible example
      description: |
        A link to a GitHub repository containing a minimal reproducible example. This repository should include as little code as possible and not include extraneous dependencies.

        Either provide a link to the repo that reproduces the bug or provide your version of the `App.tsx` file that reproduces the issue and that we can copy-paste and see the issue.

        If a reproducible example is not provided, your issue is likely to be closed.
        [Learn more about creating a minimal reproducible example](https://stackoverflow.com/help/mcve).

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: |
        Explain the issue and the steps we need to take to reproduce the issue. Include a video or screenshots if you think it may help.
        Clearly describe what the expected behavior is and what instead is actually happening.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: textarea
    attributes:
      render: text
      label: Your computer environment
      description: Run the `npx react-native info` command and paste its output in the field below.
    validations:
      required: true
