---
name: Codemod Tests

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/codemod-tests.yaml"
      - "packages/codemod/**"
  pull_request:
    paths:
      - ".github/workflows/codemod-tests.yaml"
      - "packages/codemod/**"

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v5
        with:
          run_install: false
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: pnpm

      - run: pnpm install --ignore-scripts --filter @react-native-vector-icons/codemod
      - run: pnpm run --filter @react-native-vector-icons/codemod test
