---
name: Tests

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/tests.yaml"
      - "packages/**"
      - "!packages/codemod/**"
      - "apps/icon-explorer"
  pull_request:
    paths:
      - ".github/workflows/tests.yaml"
      - "packages/**"
      - "!packages/codemod/**"
      - "apps/icon-explorer"
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Biome
        run: pnpm run lint:biome
      - name: Knip
        run: pnpm run lint:knip
      - name: Types
        run: pnpm run lint:types
